<?php
namespace App\Constants;

class ExceptionCode {
    const PREPAIDCARD_NOT_ENOUGH_EXCEPTION = 10001;
    const ALREADY_VOIDED_EXCEPTION = 10002;
    const CHOPS_NOT_ENOUGH_EXCEPTION = 10003;
    const RESOURCE_NOT_FOUND_EXCEPTION = 10004;
    const TRANSACTION_DUPLICATE_EXCEPTION = 10005;
    const CANNOT_VOID_EXCEPTION = 10006;
    const SERVER_ERROR = 99999;
}