<?php
namespace App\Constants;

class PromotionConstant {
    const TYPE_POS = 'POS';
    const TYPE_ONLINE = 'ONLINE';

    const TRIGGER_CONDITION_SPECIFIC_PRODUCT = 'SPECIFIC_PRODUCT_QTY';
    const TRIGGER_CONDITION_TOTAL_TRANSACTION_QTY = 'TOTAL_TRANSACTION_QTY';
    const TRIGGER_CONDITION_TOTAL_TRANSACTION_AMOUNT = 'TOTAL_TRANSACTION_AMOUNT';

    const CONTENT_DISCOUNT_AMOUNT = 'DISCOUNT_AMOUNT';
    const CONTENT_DISCOUNT_PERCENTAGE = 'DISCOUNT_PERCENTAGE';
    const CONTENT_SPECIFIC_PRODUCT_DISCOUNT_AMOUNT = 'SPECIFIC_PRODUCT_DISCOUNT_AMOUNT';
    const CONTENT_SPECIFIC_PRODUCT_DISCOUNT_PERCENTAGE = 'SPECIFIC_PRODUCT_DISCOUNT_PERCENTAGE';
    const CONTENT_SPECIFIC_FIXED_PRICE = 'SPECIFIC_FIXED_PRICE';
    const CONTENT_FREE_SPECIFIC_PRODUCT = 'FREE_SPECIFIC_PRODUCT';
}